version: 2
updates:
  - package-ecosystem: "bundler"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "daily"
      # Check for npm updates at 9am UTC
      time: "15:30"
    vendor: true
